In [42]:
import numpy as np
import pandas as pd

In [43]:
input_df = np.array(
    [[1,0,1,0,0],
    [1,0,0,1,0],
    [1,0,0,0,1],
    [0,1,1,0,0],
    [0,1,0,1,0],
    [0,1,0,0,1]])

In [44]:
n_msg, n_tag = input_df.shape
print(n_msg,n_tag)


6 5


In [45]:
#  build part one of matrix A for optimization 

a1 = []

for i in range(n_tag):
    # Part 1: Transpose of column i
    part1 = input_df[:, i]
    
    # Part 2: All zeros except element i which is the sum of column i 
    # this specifies # of messages that tag i can verify

    part2 = np.zeros(n_tag)
    part2[i] = np.sum(input_df[:, i])
    
    # Combine part1 and part2
    row = np.concatenate((part1, part2))
    
    # Append the row to the result matrix
    a1.append(row)

# Convert the result matrix to a NumPy array
a1 = np.array(a1)


col_names = [f"m{i+1}" for i in range(n_msg)] + [f"t{i+1}" for i in range(n_tag)]
result_df = pd.DataFrame(a1)
result_df.columns = col_names
result_df.index = [f"t{i+1}" for i in range(n_tag)]
print(result_df)


     m1   m2   m3   m4   m5   m6   t1   t2   t3   t4   t5
t1  1.0  1.0  1.0  0.0  0.0  0.0  3.0  0.0  0.0  0.0  0.0
t2  0.0  0.0  0.0  1.0  1.0  1.0  0.0  3.0  0.0  0.0  0.0
t3  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  2.0  0.0  0.0
t4  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  2.0  0.0
t5  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  2.0


In [46]:
a2 = []

# Iterate through each row of the input_df (messages)
for i in range(n_msg):
    row = input_df[i]
    # Find the indices of ones in the row (tags that verifies the message)
    ones_indices = np.where(row == 1)[0]  
    
    # Build the submatrix for the current row

    for j in ones_indices:
        # Part 1: All zeros except message i
        part1 = np.zeros(n_msg)
        part1[i] = 1
        # Part 2: All zeros except tag j
        part2 = np.zeros(n_tag)
        part2[j] = 1
        
        # Combine part1 and part2
        combined_row = np.concatenate((part1, part2))
        
        # Append the combined row to the result matrix
        a2.append(combined_row)

# Convert the result matrix to a NumPy array
a2 = np.array(a2)

col_names = [f"m{i+1}" for i in range(n_msg)] + [f"t{i+1}" for i in range(n_tag)]
result_df = pd.DataFrame(result_matrix)
result_df.columns = col_names
print(result_df)

     m1   m2   m3   m4   m5   m6   t1   t2   t3   t4   t5
0   1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
1   1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
2   0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
3   0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
4   0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
5   0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
6   0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
7   0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
8   0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0
9   0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0
10  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0
11  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0


In [53]:
a3 = []
for i in range(n_msg):
    part1 = np.zeros(n_msg+n_tag)
    part1[i] = 1
    a3.append(part1)
# Convert the result matrix to a NumPy array
a3 = np.array(a3)
print(a3)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [54]:
a4 = []
for i in range(n_msg):
    part1 = np.zeros(n_msg+n_tag)
    part1[i] = -1
    a4.append(part1)

# Convert the result matrix to a NumPy array
a4 = np.array(a4)
print(a4)

[[-1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.]]


In [57]:
a5 = []
for i in range(n_tag):
    part1 = np.zeros(n_msg+n_tag)
    part1[n_msg+i] = 1
    a5.append(part1)

# Convert the result matrix to a NumPy array
a5 = np.array(a5)
print(a5)

[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [58]:
a6 = []
for i in range(n_tag):
    part1 = np.zeros(n_msg+n_tag)
    part1[n_msg+i] = -1
    a6.append(part1)

# Convert the result matrix to a NumPy array
a6 = np.array(a6)
print(a5)

[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [60]:
# build b
epsilon = 1e-6
b1 = np.zeros(n_tag) + epsilon
print(b1)
b2 = np.zeros(a2.shape[0])
print(b2)
b3 = np.ones(n_msg+n_tag)
b4 = np.zeros(n_msg+n_tag)
b5 = np.ones(n_msg+n_tag)
b6 = -np.ones(n_msg+n_tag)
print(b6)

[1.e-06 1.e-06 1.e-06 1.e-06 1.e-06]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]


In [50]:
#build c
c = np.concatenate((np.ones(n_msg), np.zeros(n_tag)))
print(c)

[1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
