In [44]:
import numpy as np
import pandas as pd

In [45]:
K = np.array(
    [[1,0,1,0,0],
    [1,0,0,1,0],
    [1,0,0,0,1],
    [0,1,1,0,0],
    [0,1,0,1,0],
    [0,1,0,0,1]])

In [46]:
K = np.array([[ 1,  0,  0,  0,  0,  0,  1,  0,  0], # m1
              [ 1,  0,  0,  0,  0,  0,  0,  1,  0], # m2
              [ 1,  0,  0,  0,  0,  0,  0,  0,  1], # m3
              [ 0,  1,  0,  0,  0,  0,  1,  0,  0], # m4
              [ 0,  1,  0,  0,  0,  0,  0,  1,  0], # m5
              [ 0,  1,  0,  0,  0,  0,  0,  0,  1], # m6
              [ 0,  0,  1,  0,  0,  0,  1,  0,  0], # m7
              [ 0,  0,  1,  0,  0,  0,  0,  1,  0], # m8
              [ 0,  0,  1,  0,  0,  0,  0,  0,  1], # m9
              [ 0,  0,  0,  1,  0,  0,  1,  0,  0], # m10
              [ 0,  0,  0,  1,  0,  0,  0,  1,  0], # m11
              [ 0,  0,  0,  1,  0,  0,  0,  0,  1], # m12
              [ 0,  0,  0,  0,  1,  0,  1,  0,  0], # m13
              [ 0,  0,  0,  0,  1,  0,  0,  1,  0], # m14
              [ 0,  0,  0,  0,  1,  0,  0,  0,  1], # m15
              [ 0,  0,  0,  0,  0,  1,  1,  0,  0], # m16
              [ 0,  0,  0,  0,  0,  1,  0,  1,  0], # m17
              [ 0,  0,  0,  0,  0,  1,  0,  0,  1]]) # m18

In [47]:
            #  t1  t2  t3  t4  t5  t6  t7  t8  t9
K = np.array([[ 1,  0,  0,  0,  0,  0,  0,  0], # m1
              [ 1,  1,  0,  0,  0,  0,  0,  0], # m2
              [ 1,  1,  1,  0,  0,  0,  0,  0], # m3
              [ 0,  1,  1,  1,  0,  0,  0,  0], # m4
              [ 0,  0,  1,  1,  1,  0,  0,  0], # m5
              [ 0,  0,  0,  1,  1,  1,  0,  0], # m6
              [ 0,  0,  0,  0,  1,  1,  1,  0], # m7
              [ 0,  0,  0,  0,  0,  1,  1,  1], # m8
              [ 0,  0,  0,  0,  0,  0,  1,  1], # m9
              [ 0,  0,  0,  0,  0,  0,  0,  1]]) # m10

In [48]:
n_msg, n_tag = K.shape
print(n_msg,n_tag)


10 8


In [49]:
#  build part one of matrix A for optimization 

a1 = []

for i in range(n_tag):
    # Part 1: Transpose of column i
    part1 = -K[:, i]
    
    # Part 2: All zeros except element i which is the sum of column i 
    # this specifies # of messages that tag i can verify

    part2 = np.zeros(n_tag)
    part2[i] = 1
    
    # Combine part1 and part2
    row = np.concatenate((part1, part2))
    
    # Append the row to the result matrix
    a1.append(row)

# Convert the result matrix to a NumPy array
a1 = np.array(a1)


col_names = [f"m{i+1}" for i in range(n_msg)] + [f"t{i+1}" for i in range(n_tag)]
result_df = pd.DataFrame(a1)
result_df.columns = col_names
result_df.index = [f"t{i+1}" for i in range(n_tag)]
print(result_df)


     m1   m2   m3   m4   m5   m6   m7   m8   m9  m10   t1   t2   t3   t4   t5   
t1 -1.0 -1.0 -1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  \
t2  0.0 -1.0 -1.0 -1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0   
t3  0.0  0.0 -1.0 -1.0 -1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0   
t4  0.0  0.0  0.0 -1.0 -1.0 -1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
t5  0.0  0.0  0.0  0.0 -1.0 -1.0 -1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
t6  0.0  0.0  0.0  0.0  0.0 -1.0 -1.0 -1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
t7  0.0  0.0  0.0  0.0  0.0  0.0 -1.0 -1.0 -1.0  0.0  0.0  0.0  0.0  0.0  0.0   
t8  0.0  0.0  0.0  0.0  0.0  0.0  0.0 -1.0 -1.0 -1.0  0.0  0.0  0.0  0.0  0.0   

     t6   t7   t8  
t1  0.0  0.0  0.0  
t2  0.0  0.0  0.0  
t3  0.0  0.0  0.0  
t4  0.0  0.0  0.0  
t5  0.0  0.0  0.0  
t6  1.0  0.0  0.0  
t7  0.0  1.0  0.0  
t8  0.0  0.0  1.0  


In [50]:
a2 = []

# Iterate through each row of the K (messages)
for i in range(n_msg):
    row = K[i]
    # Find the indices of ones in the row (tags that verifies the message)
    ones_indices = np.where(row == 1)[0]  
    
    # Build the submatrix for the current row

    for j in ones_indices:
        # Part 1: All zeros except message i
        part1 = np.zeros(n_msg)
        part1[i] = 1
        # Part 2: All zeros except tag j
        part2 = np.zeros(n_tag)
        part2[j] = -1
        
        # Combine part1 and part2
        combined_row = np.concatenate((part1, part2))
        
        # Append the combined row to the result matrix
        a2.append(combined_row)

# Convert the result matrix to a NumPy array
a2 = np.array(a2)

col_names = [f"m{i+1}" for i in range(n_msg)] + [f"t{i+1}" for i in range(n_tag)]
result_df = pd.DataFrame(a2)
result_df.columns = col_names
print(result_df)

     m1   m2   m3   m4   m5   m6   m7   m8   m9  m10   t1   t2   t3   t4   t5   
0   1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 -1.0  0.0  0.0  0.0  0.0  \
1   0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 -1.0  0.0  0.0  0.0  0.0   
2   0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 -1.0  0.0  0.0  0.0   
3   0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 -1.0  0.0  0.0  0.0  0.0   
4   0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 -1.0  0.0  0.0  0.0   
5   0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 -1.0  0.0  0.0   
6   0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 -1.0  0.0  0.0  0.0   
7   0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 -1.0  0.0  0.0   
8   0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 -1.0  0.0   
9   0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 -1.0  0.0  0.0   
10  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 -1.0  0.0   
11  0.0  0.0  0.0  0.0  1.0 

In [51]:
a3 = []
for i in range(n_msg):
    part1 = np.zeros(n_msg+n_tag)
    part1[i] = 1
    a3.append(part1)
# Convert the result matrix to a NumPy array
a3 = np.array(a3)
print(a3)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [52]:
a4 = []
for i in range(n_msg):
    part1 = np.zeros(n_msg+n_tag)
    part1[i] = -1
    a4.append(part1)

# Convert the result matrix to a NumPy array
a4 = np.array(a4)
print(a4)

[[-1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [53]:
a5 = []
for i in range(n_tag):
    part1 = np.zeros(n_msg+n_tag)
    part1[n_msg+i] = 1
    a5.append(part1)

# Convert the result matrix to a NumPy array
a5 = np.array(a5)
print(a5)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [54]:
a6 = []
for i in range(n_tag):
    part1 = np.zeros(n_msg+n_tag)
    part1[n_msg+i] = -1
    a6.append(part1)

# Convert the result matrix to a NumPy array
a6 = np.array(a6)
print(a5)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [55]:
# build b
epsilon = 1e-6
b1 = np.zeros(n_tag)
print(b1)
b2 = np.zeros(a2.shape[0])
print(b2)
b3 = np.ones(n_msg)
b4 = np.zeros(n_msg)
b5 = np.ones(n_tag)
b6 = -np.ones(n_tag)
print(b6)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[-1. -1. -1. -1. -1. -1. -1. -1.]


In [56]:
#build c
C = np.concatenate((np.ones(n_msg), np.zeros(n_tag)))
print(C)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


In [57]:

A = np.concatenate((a1, a2, a3, a4, a5, a6), axis=0)

B = np.concatenate((b1,b2,b3,b4,b5,b6))


In [58]:
print(C.shape)
print(A.shape)
print(B.shape)

(18,)
(68, 18)
(68,)


In [59]:
from pulp import LpMinimize, LpProblem, LpVariable, lpSum, PULP_CBC_CMD

prob = LpProblem("Binary LP Problem", LpMinimize)

# Define the variables
x = [LpVariable(f'x{i}', cat='Binary') for i in range(len(C))]

# Define the objective function
prob += lpSum(C[i] * x[i] for i in range(len(C)))

# Define the constraints
for i in range(len(A)):
    prob += lpSum(A[i][j] * x[j] for j in range(len(C))) <= B[i]

# Solve the problem
prob.solve(PULP_CBC_CMD())

# Print the results
print("Status:", prob.status)
print("Objective value:", prob.objective.value())
for i in range(len(C)):
    print(f"x{i+1}:", x[i].value())

Welcome to the CBC MILP Solver 
Version: 2.10.3 
Build Date: Dec 15 2019 

command line - /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pulp/solverdir/cbc/osx/64/cbc /var/folders/jv/12n64fl91y1d9jr6561fpx2c0000gn/T/53252c60ddda4a809b46604a75ac88d9-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /var/folders/jv/12n64fl91y1d9jr6561fpx2c0000gn/T/53252c60ddda4a809b46604a75ac88d9-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 73 COLUMNS
At line 236 RHS
At line 305 BOUNDS
At line 324 ENDATA
Problem MODEL has 68 rows, 18 columns and 116 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 3 - 0.00 seconds
Cgl0002I 8 variables fixed
Cgl0004I processed model has 8 rows, 10 columns (10 integer (10 of which binary)) and 24 elements
Cutoff increment increased from 1e-05 to 0.9999
Cbc0038I Initial state - 0 integers unsatisfied sum - 0
Cbc0038I

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pulp/pulp.py:1316: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")
