In [12]:
import numpy as np
import pandas as pd

In [13]:
K = np.array(
    [[1,0,1,0,0],
    [1,0,0,1,0],
    [1,0,0,0,1],
    [0,1,1,0,0],
    [0,1,0,1,0],
    [0,1,0,0,1]])

In [14]:
n_msg, n_tag = K.shape
print(n_msg,n_tag)

6 5


In [15]:
A = np.transpose(K)
B = np.ones(n_tag)
C = np.ones(n_msg)
print(A)

[[1 1 1 0 0 0]
 [0 0 0 1 1 1]
 [1 0 0 1 0 0]
 [0 1 0 0 1 0]
 [0 0 1 0 0 1]]


In [16]:
from pulp import LpMinimize, LpProblem, LpVariable, lpSum, PULP_CBC_CMD

prob = LpProblem("Binary LP Problem", LpMinimize)

# Define the variables
x = [LpVariable(f'x{i}', cat='Binary') for i in range(len(C))]

# Define the objective function
prob += lpSum(C[i] * x[i] for i in range(len(C)))

# Define the constraints
for i in range(len(A)):
    prob += lpSum(A[i][j] * x[j] for j in range(len(C))) >= B[i]

# Solve the problem
prob.solve(PULP_CBC_CMD())

# Print the results
print("Status:", prob.status)
print("Objective value:", prob.objective.value())
for i in range(len(C)):
    print(f"x{i+1}:", x[i].value())

Welcome to the CBC MILP Solver 
Version: 2.10.3 
Build Date: Dec 15 2019 

command line - /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pulp/solverdir/cbc/osx/64/cbc /var/folders/jv/12n64fl91y1d9jr6561fpx2c0000gn/T/1259038340ce40c9a8a28089d3e7aab9-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /var/folders/jv/12n64fl91y1d9jr6561fpx2c0000gn/T/1259038340ce40c9a8a28089d3e7aab9-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 10 COLUMNS
At line 41 RHS
At line 47 BOUNDS
At line 54 ENDATA
Problem MODEL has 5 rows, 6 columns and 12 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 3 - 0.00 seconds
Cgl0004I processed model has 5 rows, 6 columns (6 integer (6 of which binary)) and 12 elements
Cutoff increment increased from 1e-05 to 0.9999
Cbc0038I Initial state - 0 integers unsatisfied sum - 0
Cbc0038I Solution found of 3
Cbc0038I Before

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pulp/pulp.py:1316: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")
